name: Train
version: ${project.version}
main: me.wincho.train.Train
api-version: 1.16
authors: [ wincho ]
commands:
  create_train:
    description: create train
    usage: /create_train [block x] [block y] [block z] [train count (max 10)] [train speed] [max user count]
  /station:
    description: create station
    usage: //station [num]